# Generated by Django 2.1.5 on 2019-02-14 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('model', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('model', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2048)),
                ('city', models.CharField(max_length=50)),
                ('contact', models.CharField(default='0000000', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Phone'),
        ),
    ]
