# Generated by Django 2.1.5 on 2019-02-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('price', models.FloatField(max_length=255)),
            ],
        ),
    ]
