# Generated by Django 2.1.5 on 2019-02-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190210_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop', models.ManyToManyField(to='product.Laptop')),
                ('phone', models.ManyToManyField(to='product.Phone')),
            ],
        ),
    ]
