# Generated by Django 2.1.5 on 2019-02-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190211_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=2048)),
            ],
        ),
        migrations.RemoveField(
            model_name='gadgets',
            name='laptop',
        ),
        migrations.RemoveField(
            model_name='gadgets',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Gadgets',
        ),
    ]
